# Generated by Django 4.1.7 on 2023-03-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField()),
                ('moving_from', models.CharField(max_length=100)),
                ('moving_to', models.CharField(max_length=100)),
            ],
        ),
    ]
