# Generated by Django 4.1.7 on 2023-03-24 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('car_registration', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vihicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.CharField(choices=[('Trailer', 'Trailer'), ('Bakkie', 'Bakkie'), ('Truck', 'Truck')], default='Trailer', max_length=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.IntegerField()),
                ('car_registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Driver.driver')),
            ],
        ),
    ]
